version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  app:
    image: java_api-app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - backend
    volumes:
      - ./CONJUR_CA:/tmp/conjur-connect/CONJUR_CA

networks:
  backend:

volumes:
  db-data:
